### ISSUE TITLE
Fails on this file

### ISSUE THREAD

**Issue by loopless** [TinyTinni/FileSTL#2]
I found this a very interesting use of Boost::spirit and could be a useful easy to use STL reader, however it returns numerical garbage in the normals and vertices when presented with this file.

[window.zip](https://github.com/TinyTinni/FileSTL/files/3412147/window.zip)

**Comment by TinyTinni** [comment]
Hi, thanks for having interest in this project.
Looks like the parser is not working, when the mesh has no name (first/last line "solid <name>" where <name> is optional)

What I can see right now, is, that on [line 93](https://github.com/TinyTinni/FileSTL/blob/master/stlio.hpp#L93) the plus has to be replaced with a Kleene (the *) operator.

I will test it later on, not sure if I can do this today.

**Comment by loopless** [comment]
Thank you for looking at it this issue! I found it a great "tutorial" on a real-world use of Boost::spirit

**Comment by TinyTinni** [comment]
Took a bit longer, since the Kleene operator would cause initializing problems.
For now, the text present or an empty string is assigned for the header.
