### ISSUE TITLE
missing one space in writer

### ISSUE THREAD

**Issue by HidenCrew** [TinyTinni/FileSTL#3]
Hi Matthias,
Great project, but write_ascii() seems missing one space between string "vertex" and the vertex data,
`for (size_t j = 0; j < 3; ++j)`
`{`
`    out << "\t\t\tvertex"` ==> missing one space here
`           << s.vertices[3 * i + j][0] << " "`

Some 3D model reader would stuck by this minor typo.

**Comment by TinyTinni** [comment]
Added a space.
Thanks for notifying.
